### ISSUE TITLE
Realtime fails to launch

### ISSUE THREAD

**Issue by scottbw** [e-ucm/rage-analytics#64]
Error log:

Attaching to rage_realtime_1
realtime_1     | Can not write to /root/.m2/copy_reference_file.log. Wrong volume permissions? Carrying on ...
rage_realtime_1 exited with code 0

**Comment by RotaruDan** [comment]
Don't worry, Exited with code 0 it means it has performed its function (create the analysis topology: realtime.jar) and finished. The realtime.jar is uploaded to Storm (nimbus and supervisor) afterwards. 

This is the expected behavior. Furthermore the back-log.txt from https://github.com/e-ucm/rage-analytics/issues/62 displays that the realtime.jar has been successfully submitted to storm lines 130 - 160:

```
back           | Shell executing command /app/storm_vol/bin/storm jar /app/output/realtime-jar-with-dependencies.jar org.apache.storm.flux.Flux --remote /app/flux.yml
back           | Running: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/app/storm_vol -Dstorm.log.dir=/app/storm_vol/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /app/storm_vol/lib/ring-cors-0.1.5.jar:/app/storm_vol/lib/log4j-slf4j-impl-2.8.2.jar:/app/storm_vol/lib/log4j-over-slf4j-1.6.6.jar:/app/storm_vol/lib/minlog-1.3.0.jar:/app/storm_vol/lib/servlet-api-2.5.jar:/app/storm_vol/lib/storm-core-1.1.1.jar:/app/storm_vol/lib/log4j-api-2.8.2.jar:/app/storm_vol/lib/log4j-core-2.8.2.jar:/app/storm_vol/lib/disruptor-3.3.2.jar:/app/storm_vol/lib/storm-rename-hack-1.1.1.jar:/app/storm_vol/lib/asm-5.0.3.jar:/app/storm_vol/lib/slf4j-api-1.7.21.jar:/app/storm_vol/lib/kryo-3.0.3.jar:/app/storm_vol/lib/clojure-1.7.0.jar:/app/storm_vol/lib/objenesis-2.1.jar:/app/storm_vol/lib/reflectasm-1.10.1.jar:/app/output/realtime-jar-with-dependencies.jar:/app/storm_vol/conf:/app/storm_vol/bin -Dstorm.jar=/app/output/realtime-jar-with-dependencies.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} org.apache.storm.flux.Flux --remote /app/flux.yml
back           | ███████╗██╗     ██╗   ██╗██╗  ██╗
back           | ██╔════╝██║     ██║   ██║╚██╗██╔╝
back           | █████╗  ██║     ██║   ██║ ╚███╔╝
back           | ██╔══╝  ██║     ██║   ██║ ██╔██╗
back           | ██║     ███████╗╚██████╔╝██╔╝ ██╗
back           | ╚═╝     ╚══════╝ ╚═════╝ ╚═╝  ╚═╝
back           | +-         Apache Storm        -+
back           | +-  data FLow User eXperience  -+
back           | Version: 1.1.1
back           | Parsing file: /app/flux.yml
back           | 729  [main] INFO  o.a.s.f.p.FluxParser - loading YAML from input stream...
back           | 736  [main] INFO  o.a.s.f.p.FluxParser - Not performing property substitution.
back           | 736  [main] INFO  o.a.s.f.p.FluxParser - Not performing environment variable substitution.
back           | 808  [main] INFO  o.a.s.f.FluxBuilder - A topology source has been specified...
back           | 1981 [main] WARN  o.a.s.u.Utils - STORM-VERSION new 1.1.1 old null
back           | 1982 [main] INFO  o.a.s.f.Flux - Running remotely...
back           | 1983 [main] INFO  o.a.s.f.Flux - Deploying topology in an ACTIVE state...
back           | 2003 [main] INFO  o.a.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -5048163926020772177:-9107267961621859741
back           | 2192 [main] INFO  o.a.s.u.NimbusClient - Found leader nimbus : 57788aec1a68:6627
back           | 2224 [main] INFO  o.a.s.s.a.AuthUtils - Got AutoCreds []
back           | 2237 [main] INFO  o.a.s.u.NimbusClient - Found leader nimbus : 57788aec1a68:6627
back           | 2263 [main] INFO  o.a.s.StormSubmitter - Uploading dependencies - jars...
back           | 2265 [main] INFO  o.a.s.StormSubmitter - Uploading dependencies - artifacts...
back           | 2265 [main] INFO  o.a.s.StormSubmitter - Dependency Blob keys - jars : [] / artifacts : []
back           | 2276 [main] INFO  o.a.s.StormSubmitter - Uploading topology jar /app/output/realtime-jar-with-dependencies.jar to assigned location: /app/nimbus/inbox/stormjar-e27cf447-70b4-4f7a-8b20-02a48243b43b.jar
back           | 2849 [main] INFO  o.a.s.StormSubmitter - Successfully uploaded topology jar to assigned location: /app/nimbus/inbox/stormjar-e27cf447-70b4-4f7a-8b20-02a48243b43b.jar
back           | 2850 [main] INFO  o.a.s.StormSubmitter - Submitting topology defaultstormanalysis in distributed mode with conf {"elasticsearchUrl":"elastic5","storm.zookeeper.topology.auth.scheme":"digest","topology.workers":1,"zookeeperUrl":"kzk:2181","topology.max.spout.pending":1,"topicName":"defaultkafkaanalysistopic","storm.zookeeper.topology.auth.payload":"-5048163926020772177:-9107267961621859741"}
back           | 2850 [main] WARN  o.a.s.u.Utils - STORM-VERSION new 1.1.1 old 1.1.1
back           | 6660 [main] INFO  o.a.s.StormSubmitter - Finished submitting topology: defaultstormanalysis
```

**Comment by RotaruDan** [comment]
What bothers me more is the error from https://github.com/e-ucm/rage-analytics/issues/62 (back-log.txt lines 536 - 560:

```
back           | /app/routes/kibana.js:1193
back           |                         if (response.hits.hits && response.hits.hits.length > 0) {
back           |                                          ^
back           |
back           | TypeError: Cannot read property 'hits' of undefined
back           |     at /app/routes/kibana.js:1193:42
back           |     at respond (/app/node_modules/elasticsearch/src/lib/transport.js:326:9)
back           |     at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:266:7)
back           |     at HttpConnector.<anonymous> (/app/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
back           |     at IncomingMessage.bound (/app/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
back           |     at emitNone (events.js:110:20)
back           |     at IncomingMessage.emit (events.js:207:7)
back           |     at endReadableNT (_stream_readable.js:1059:12)
back           |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
back           |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

This error has been solved but we have not released a new version of the docker images. We are working in doing so as soon as possible and we will update the docker-compose.yml https://github.com/e-ucm/rage-analytics/blob/master/docker-compose.yml

If you are on a hurry, and want to try it yourself, before we finish the final debugging stage, you can replace the contents of your docker-compose.yml file with the contents of this updated version (yet we're finishing the final tests for it): https://raw.githubusercontent.com/e-ucm/rage-analytics/36809018e41fe6667e3042a3896d58842fd28c66/docker-compose.yml

Once you've done that, I strongly recommend you, if you don't have critical data, to purge everything docker related:

```
sudo rm -rf ./data
sudo ./rage-analytics.sh purge
sudo service docker stop
sudo rm -rf /var/lib/docker
sudo servide docker start
sudo ./rage-analytics.sh restart

```

This should clean-install all the updated images from the updated docker-compose: https://raw.githubusercontent.com/e-ucm/rage-analytics/36809018e41fe6667e3042a3896d58842fd28c66/docker-compose.yml

Note that this is still a pre-release version, but in the final staged of testing, and will be released as a stable release after a few more tests. :)

**Comment by scottbw** [comment]
Any idea when the stable release will be available?

**Comment by gorco** [comment]
The release is already published 
https://github.com/e-ucm/rage-analytics
